CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE START 1 INCREMENT 1;

CREATE TABLE IF NOT EXISTS CAMPAIGN
(
    ID            INT8 NOT NULL,
    CAMPAIGN_NAME VARCHAR(50),
    END_DATE      DATE NOT NULL,
    START_DATE    DATE NOT NULL,
    COMPANY_ID    INT8 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS COMPANY
(
    ID           INT8 NOT NULL,
    COMPANY_NAME VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER
(
    ID               INT8 NOT NULL,
    APARTMENT_NUMBER INT4,
    COUNTRY          VARCHAR(50),
    STREET           VARCHAR(50),
    AGE              INT4 NOT NULL CHECK (AGE >= 13),
    COUPON_CODE      VARCHAR(50),
    NAME             VARCHAR(50),
    EMAIL            VARCHAR(50) NOT NULL,
    UNIQUE (EMAIL),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LOG_ENTRY
(
    ID             INT8 NOT NULL,
    COUPON_CODE    VARCHAR(10) NOT NULL,
    EMAIL          VARCHAR(50) NOT NULL,
    IS_WINNER      BOOLEAN NOT NULL,
    SUBMITTED_DATE DATE NOT NULL,
    TERRITORY      VARCHAR(50) NOT NULL,
    UNIQUE (EMAIL),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID           INT8 NOT NULL,
    COUPON_CODE  VARCHAR(50),
    PRODUCT_NAME VARCHAR(50),
    COMPANY_ID   INT8 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RULE
(
    ID                      INT8 NOT NULL,
    MAXIMUM_WINNERS_PER_DAY INT4 NOT NULL,
    NTH_ENTRY               INT4 NOT NULL,
    NUMBER_OF_PRODUCTS      INT4 NOT NULL,
    TERRITORY_ID            INT8,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TERRITORY
(
    ID             INT8 NOT NULL,
    TERRITORY_NAME VARCHAR(50) NOT NULL,
    CAMPAIGN_ID    INT8 NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE CAMPAIGN
    ADD CONSTRAINT  FK_COMPANY_CAMPAIGN_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY;

ALTER TABLE PRODUCT
    ADD CONSTRAINT FK_COMPANY_PRODUCT_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY;

ALTER TABLE RULE
    ADD CONSTRAINT FK_RULE_TERRITORY_ID FOREIGN KEY (TERRITORY_ID) REFERENCES TERRITORY;

ALTER TABLE TERRITORY
    ADD CONSTRAINT FK_CAMPAIGN_TERRITORY_ID FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN;
